"""
Data Architecture: SQLModel Schemas and Tables.

This module defines the data contracts for the Retail Inventory API.
It uses SQLModel to unify Pydantic validation (for API requests) and
SQLAlchemy ORM (for database persistence).
"""

from enum import Enum
from typing import Optional

from pydantic import field_validator
from sqlmodel import Field, SQLModel


class Category(str, Enum):
    TEES = "Tees"
    SWEATERS = "Sweaters"
    SHIRTS = "Shirts"
    PANTS = "Pants"
    SHORTS = "Shorts"
    TANK_TOPS = "Tank Tops"
    OTHER = "Other"


class ProductBase(SQLModel):
    """
    Shared attributes for a Product.

    Serves as the foundation for both the database table and the
    API request/response schemas to ensure data consistency.
    """

    category: Category = Field(
        default=Category.OTHER,
        description="Product category, must be one of the predefined categories.",
    )
    name: str = Field(
        max_length=50,
        min_length=1,
        index=True,  # Adding an index for faster name-based searches later
        description="Name of the product.",
    )

    @field_validator("name")
    @classmethod
    def name_must_not_be_empty(cls, value):
        if not value.strip():
            raise ValueError("Product name must not be empty.")
        return value.strip()

    price: float = Field(gt=0, description="Unit price, must be greater than zero.")
    coming_soon: bool = Field(
        default=False,
        description="Flag indicating an upcoming product that will be available soon.",
    )


class Size(str, Enum):
    S_M = "S-M"
    L_XL = "L-XL"
    OS = "OS"


class ProductVariantBase(SQLModel):
    """
    Shared attributes for a Product Variant.

    This model captures the specific details of a product variant, such as size, color and stock information,
    while inheriting common product attributes from ProductBase.
    """

    size: Size = Field(
        default=Size.OS,
        description="Size of the product variant, must be one of the predefined sizes.",
    )
    color: Optional[str] = Field(
        default=None,
        max_length=30,
        min_length=1,
        index=True,  # Adding an index for faster color-based searches later
        description="Color of the product variant, optional but if provided must be a non-empty string.",
    )

    @field_validator("color")
    @classmethod
    def color_must_not_be_empty(cls, value):
        if value is not None and not value.strip():
            raise ValueError("Color must not be an empty string if provided.")
        return value.strip() if value is not None else None

    quantity: int = Field(
        default=0, ge=0, description="Current stock quantity in the warehouse."
    )
    in_stock: bool = Field(
        default=True,
        description="Flag indicating if the product is available for sale.",
    )
    
class Product(ProductBase, table=True):
    """
    The Database Table Model.

    Setting 'table=True' tells SQLModel to map this class to a
    PostgreSQL table. This represents the 'Source of Truth' in the DB.
    """

    # This class serves a dual purpose:
    # 1. Pydantic Model (API Validation)
    # 2. SQLAlchemy Model (Database Table Mapping)
    id: Optional[int] = Field(
        default=None,
        primary_key=True,
        description="Unique primary key automatically generated by PostgreSQL.",
    )

class ProductVariant(ProductVariantBase, table=True):
    """
    The Database Table Model for Product Variants.

    This class represents the specific variants of a product (e.g., different sizes and colors) in the database.
    """

    id: Optional[int] = Field(
        default=None,
        primary_key=True,
        description="Unique primary key automatically generated by PostgreSQL.",
    )
    product_id: int = Field(
        foreign_key="product.id",
        description="Foreign key linking to the parent product.",
    )