"""
Data Architecture: SQLModel Schemas and Tables.

This module defines the data contracts for the Retail Inventory API.
It uses SQLModel to unify Pydantic validation (for API requests) and
SQLAlchemy ORM (for database persistence).
"""

from sqlmodel import SQLModel, Field
from typing import Optional


class ProductBase(SQLModel):
    """
    Shared attributes for a Product.

    Serves as the foundation for both the database table and the
    API request/response schemas to ensure data consistency.
    """

    name: str = Field(
        max_length=50,
        index=True,  # Adding an index for faster name-based searches later
        description="Name of the product.",
    )
    price: float = Field(gt=0, description="Unit price, must be greater than zero.")
    quantity: int = Field(
        default=0, ge=0, description="Current stock quantity in the warehouse."
    )
    in_stock: bool = Field(
        default=True,
        description="Flag indicating if the product is available for sale.",
    )


class Product(ProductBase, table=True):
    """
    The Database Table Model.

    Setting 'table=True' tells SQLModel to map this class to a
    PostgreSQL table. This represents the 'Source of Truth' in the DB.
    """

    id: Optional[int] = Field(
        default=None,
        primary_key=True,
        description="Unique primary key automatically generated by PostgreSQL.",
    )


class ProductCreate(ProductBase):
    """
    Schema for creating a new product via POST requests.

    Inherits all fields from ProductBase. The 'id' is excluded because
    it is generated by the database, not provided by the client.
    """

    # Overriding in_stock to allow it to be optional during creation
    in_stock: Optional[bool] = None


class ProductUpdate(SQLModel):
    """
    Schema for partial updates (PATCH requests).

    All fields are marked as Optional to allow clients to update
    only specific attributes (e.g., just the quantity) without
    sending the entire object.
    """

    name: Optional[str] = Field(default=None, max_length=50)
    price: Optional[float] = Field(default=None, gt=0)
    quantity: Optional[int] = Field(default=None, ge=0)
    in_stock: Optional[bool] = None
