"""
Product models: SQLModel schemas and table definitions for the Product entity.
"""

from enum import Enum
from typing import Optional
from uuid import UUID, uuid4

from pydantic import field_validator
from sqlmodel import Field, SQLModel


class HealthResponse(SQLModel):
    """
    Schema for the health check endpoint response.

    This simple model ensures that the API returns a consistent structure
    for health checks, which can be easily extended in the future if needed.
    """

    status: str = Field(
        default="ok",
        description="Indicates the health status of the API. Expected to be 'ok' when healthy.",
    )
    uptime: float = Field(
        default=0.0,
        description="The uptime of the API in seconds. Useful for monitoring and diagnostics.",
    )
    version: str


class Category(str, Enum):
    """Predefined product categories for inventory classification."""

    TEES = "Tees"
    SWEATERS = "Sweaters"
    SHIRTS = "Shirts"
    PANTS = "Pants"
    SHORTS = "Shorts"
    TANK_TOPS = "Tank Tops"
    OTHER = "Other"


class ProductBase(SQLModel):
    """
    Shared attributes for a Product.

    Serves as the foundation for both the database table and the
    API request/response schemas to ensure data consistency.
    """

    category: Category = Field(
        default=Category.OTHER,
        description="Product category, must be one of the predefined categories.",
    )
    name: str = Field(
        max_length=50,
        min_length=1,
        index=True,  # Adding an index for faster name-based searches later
        description="Name of the product.",
    )

    @field_validator("name")
    @classmethod
    def name_must_not_be_empty(cls, value):
        """Validator to ensure that the product name is not an empty string."""
        if not value.strip():
            raise ValueError("Product name must not be empty.")
        return value.strip()

    color: str = Field(
        default=None,
        max_length=30,
        min_length=1,
        index=True,  # Adding an index for faster color-based searches later
        description="Color of the product, optional but if provided must be a non-empty string.",
    )

    @field_validator("color")
    @classmethod
    def color_must_not_be_empty(cls, value):
        """Validator to ensure that the color is not an empty string if provided."""
        if value is not None and not value.strip():
            raise ValueError("Color must not be an empty string if provided.")
        return value.strip() if value is not None else None

    price: float = Field(gt=0, description="Unit price, must be greater than zero.")

    collection: str = Field(
        default=None,
        max_length=10,
        min_length=4,
        index=True,
        description="Flag indicating under which collection the product is released",
    )

    @field_validator("collection")
    @classmethod
    def collection_must_not_be_empty(cls, value):
        """Validator to ensure that the collection is not an empty string if provided."""
        if value is not None and not value.strip():
            raise ValueError("Collection must not be an empty string if provided.")
        return value.strip() if value is not None else None

    coming_soon: bool = Field(
        default=False,
        description="Flag indicating an upcoming product that will be available soon.",
    )


class Product(ProductBase, table=True):
    """
    The Database Table Model.

    Setting 'table=True' tells SQLModel to map this class to a
    PostgreSQL table. This represents the 'Source of Truth' in the DB.
    """

    # This class serves a dual purpose:
    # 1. Pydantic Model (API Validation)
    # 2. SQLAlchemy Model (Database Table Mapping)
    id: UUID = Field(
        default_factory=uuid4,
        primary_key=True,
        description="UUID primary key.",
    )
    sku: str = Field(
        max_length=7,
        description="Auto-generated SKU based on category prefix and sequential number (e.g. TS-0001).",
        unique=True,
    )


class ProductCreate(ProductBase):
    """
    Schema for creating a new product via POST requests.

    Inherits all fields from ProductBase. The 'id' is excluded because
    it is generated by the database, not provided by the client.
    """

    # Overriding coming_soon to allow it to be optional during creation
    coming_soon: Optional[bool] = None


class ProductUpdate(SQLModel):
    """
    Schema for partial updates (PATCH requests).

    All fields are marked as Optional to allow clients to update
    only specific attributes (e.g., just the price) without
    sending the entire object.
    """

    category: Optional[Category] = None
    name: Optional[str] = Field(default=None, max_length=50, min_length=1)
    color: Optional[str] = Field(default=None, max_length=30, min_length=1)
    price: Optional[float] = Field(default=None, gt=0)
    collection: Optional[str] = Field(default=None, max_length=10, min_length=4)
    coming_soon: Optional[bool] = None
