"""
Variant models: SQLModel schemas and table definitions for the ProductVariant entity.
"""

from enum import Enum
from typing import Optional
from uuid import UUID, uuid4

from sqlalchemy import Column, ForeignKey
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlmodel import Field, SQLModel


class Size(str, Enum):
    """Predefined sizes for product variants."""

    S_M = "S-M"
    L_XL = "L-XL"
    OS = "OS"


class ProductVariantBase(SQLModel):
    """
    Shared attributes for a Product Variant.

    This model captures the specific details of a product variant, such as size, color and stock information,
    while inheriting common product attributes from ProductBase.
    """

    size: Size = Field(
        default=Size.OS,
        description="Size of the product variant, must be one of the predefined sizes.",
    )
    quantity: int = Field(
        default=0, ge=0, description="Current stock quantity in the warehouse."
    )
    in_stock: bool = Field(
        default=True,
        description="Flag indicating if the product is available for sale.",
    )


class ProductVariant(ProductVariantBase, table=True):
    """
    The Database Table Model for Product Variants.

    This class represents the specific variants of a product (e.g., different sizes and colors) in the database.
    """

    id: UUID = Field(
        default_factory=uuid4,
        primary_key=True,
        description="UUID primary key.",
    )
    product_id: UUID = Field(
        sa_column=Column(
            PGUUID(as_uuid=True),
            ForeignKey("product.id", ondelete="CASCADE"),
            nullable=False,
        ),
        description="UUID foreign key linking to the parent product.",
    )


class ProductVariantCreate(ProductVariantBase):
    """
    Schema for creating a new product variant via POST requests.

    Inherits all fields from ProductVariantBase. The 'id' is excluded because
    it is generated by the database, not provided by the client.
    """

    # Overriding in_stock to allow it to be optional during creation
    in_stock: Optional[bool] = None


class ProductVariantUpdate(SQLModel):
    """
    Schema for partial updates (PATCH requests) of product variants.

    All fields are marked as Optional to allow clients to update
    only specific attributes (e.g., just the quantity) without
    sending the entire object.
    """

    size: Optional[Size] = None
    quantity: Optional[int] = Field(default=None, ge=0)
    in_stock: Optional[bool] = None
